#!/usr/bin/env bash
# =============================================================================
# pitr-restore.sh – Point-In-Time Recovery for the Very-Prince PostgreSQL cluster
# =============================================================================
#
# OVERVIEW
# --------
# This script instructs CloudNativePG to create a NEW cluster restored from
# a WAL archive stored in MinIO up to a target recovery time.  A new cluster
# is created so the current primary is untouched until you are confident the
# recovery succeeded.
#
# PREREQUISITES
# -------------
#   • kubectl configured with access to the very-prince namespace
#   • CloudNativePG operator running (kubectl cnpg plugin optional but helpful)
#   • MinIO reachable at http://minio.very-prince.svc.cluster.local:9000
#   • The source cluster (very-prince-pg) has WAL archiving enabled
#
# USAGE
# -----
#   # Restore to a specific point in time (ISO 8601 UTC):
#   ./pitr-restore.sh "2026-07-24T18:00:00Z"
#
#   # Restore to the latest available WAL position:
#   ./pitr-restore.sh latest
#
#   # Dry-run (print the manifest without applying):
#   DRY_RUN=true ./pitr-restore.sh "2026-07-24T18:00:00Z"
#
# POST-RECOVERY
# -------------
#   1. Validate the recovered cluster:
#        kubectl exec -n very-prince very-prince-pg-restore-1 -- \
#          psql -U postgres -d very_prince -c "SELECT count(*) FROM \"Transaction\";"
#
#   2. If the recovery is correct, promote it to production by updating
#      the application DATABASE_URL to point at:
#        very-prince-pg-restore-rw.very-prince.svc.cluster.local:5432
#
#   3. After validation, delete the old cluster if desired:
#        kubectl delete cluster very-prince-pg -n very-prince
#
#   4. (Optional) Rename the restored cluster back to 'very-prince-pg' by
#      exporting its data and reimporting, or simply update all references.
#
# =============================================================================
set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
NAMESPACE="${NAMESPACE:-very-prince}"
SOURCE_CLUSTER="${SOURCE_CLUSTER:-very-prince-pg}"
RESTORE_CLUSTER="${RESTORE_CLUSTER:-very-prince-pg-restore}"
MINIO_ENDPOINT="${MINIO_ENDPOINT:-http://minio.very-prince.svc.cluster.local:9000}"
MINIO_BUCKET="${MINIO_BUCKET:-very-prince-wal}"
DRY_RUN="${DRY_RUN:-false}"
KUBECTL="${KUBECTL:-kubectl}"

# ── Argument parsing ─────────────────────────────────────────────────────────
TARGET_TIME="${1:-}"

if [[ -z "$TARGET_TIME" ]]; then
  echo "❌  Usage: $0 <ISO8601-target-time | latest>"
  echo "   Example: $0 \"2026-07-24T18:00:00Z\""
  echo "   Example: $0 latest"
  exit 1
fi

# ── Validate target time format ───────────────────────────────────────────────
if [[ "$TARGET_TIME" != "latest" ]]; then
  if ! date -d "$TARGET_TIME" &>/dev/null 2>&1 && \
     ! date -j -f "%Y-%m-%dT%H:%M:%SZ" "$TARGET_TIME" &>/dev/null 2>&1; then
    echo "⚠️  Warning: Could not validate '$TARGET_TIME' as a date on this system."
    echo "   Continuing anyway – CloudNativePG will reject an invalid timestamp."
  fi
fi

# ── Print banner ──────────────────────────────────────────────────────────────
echo "========================================================"
echo " Very-Prince PostgreSQL PITR Restore"
echo "========================================================"
echo " Namespace      : $NAMESPACE"
echo " Source cluster : $SOURCE_CLUSTER"
echo " Restore cluster: $RESTORE_CLUSTER"
echo " Target time    : $TARGET_TIME"
echo " MinIO endpoint : $MINIO_ENDPOINT"
echo " Dry run        : $DRY_RUN"
echo "========================================================"

# ── Check for existing restore cluster ───────────────────────────────────────
if $KUBECTL get cluster "$RESTORE_CLUSTER" -n "$NAMESPACE" &>/dev/null; then
  echo ""
  echo "⚠️  A cluster named '$RESTORE_CLUSTER' already exists in namespace '$NAMESPACE'."
  read -r -p "   Delete it and start fresh? [y/N] " CONFIRM
  if [[ "${CONFIRM,,}" == "y" ]]; then
    echo "🗑  Deleting existing restore cluster..."
    $KUBECTL delete cluster "$RESTORE_CLUSTER" -n "$NAMESPACE"
    echo "⏳ Waiting for deletion to complete..."
    $KUBECTL wait --for=delete cluster/"$RESTORE_CLUSTER" \
      -n "$NAMESPACE" --timeout=120s || true
  else
    echo "Aborting. Choose a different RESTORE_CLUSTER name or delete it manually."
    exit 1
  fi
fi

# ── Build recovery target spec ────────────────────────────────────────────────
if [[ "$TARGET_TIME" == "latest" ]]; then
  RECOVERY_TARGET_BLOCK=""
else
  RECOVERY_TARGET_BLOCK="
    recoveryTarget:
      targetTime: \"${TARGET_TIME}\"
      targetAction: promote"
fi

# ── Build the Cluster manifest ────────────────────────────────────────────────
MANIFEST=$(cat <<EOF
---
# CloudNativePG PITR Restore Cluster
# Generated by pitr-restore.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Target time: ${TARGET_TIME}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${RESTORE_CLUSTER}
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: ${RESTORE_CLUSTER}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: very-prince
    very-prince/restore: "true"
spec:
  instances: 1    # single instance for validation; scale up after confirmation

  imageName: ghcr.io/cloudnative-pg/postgresql:15.6

  bootstrap:
    recovery:
      source: ${SOURCE_CLUSTER}
      ${RECOVERY_TARGET_BLOCK}

  externalClusters:
    - name: ${SOURCE_CLUSTER}
      barmanObjectStore:
        destinationPath: s3://${MINIO_BUCKET}/
        endpointURL: ${MINIO_ENDPOINT}
        s3Credentials:
          accessKeyId:
            name: minio-s3-secret
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: minio-s3-secret
            key: SECRET_ACCESS_KEY
        wal:
          maxParallel: 4

  storage:
    size: 20Gi
    storageClass: standard

  superuserSecret:
    name: very-prince-pg-superuser-secret

  # Do NOT archive WAL from the restore cluster to avoid corrupting source
  # backup: {}

  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
EOF
)

# ── Apply or print ────────────────────────────────────────────────────────────
if [[ "$DRY_RUN" == "true" ]]; then
  echo ""
  echo "──────────────── DRY RUN – Manifest (not applied) ────────────────"
  echo "$MANIFEST"
  echo "───────────────────────────────────────────────────────────────────"
  echo "✅ Dry-run complete. Re-run without DRY_RUN=true to apply."
  exit 0
fi

echo ""
echo "🚀 Applying restore cluster manifest..."
echo "$MANIFEST" | $KUBECTL apply -f -

echo ""
echo "⏳ Waiting for restore cluster to initialise (timeout: 15 min)..."
$KUBECTL wait cluster/"$RESTORE_CLUSTER" \
  -n "$NAMESPACE" \
  --for=condition=Ready \
  --timeout=900s

echo ""
echo "✅ Restore cluster '${RESTORE_CLUSTER}' is Ready!"
echo ""
echo "──────────────── Validation commands ────────────────────────────────"
echo "# Connect to restored cluster:"
echo "kubectl exec -n ${NAMESPACE} ${RESTORE_CLUSTER}-1 -- \\"
echo "  psql -U postgres -d very_prince -c \"SELECT now();\""
echo ""
echo "# Count transactions (sanity check):"
echo "kubectl exec -n ${NAMESPACE} ${RESTORE_CLUSTER}-1 -- \\"
echo "  psql -U postgres -d very_prince -c 'SELECT count(*) FROM \"Transaction\";'"
echo ""
echo "# Tail PostgreSQL logs:"
echo "kubectl logs -n ${NAMESPACE} ${RESTORE_CLUSTER}-1 -f"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "After validation, update DATABASE_URL to:"
echo "  postgresql://very_prince_app:<password>@${RESTORE_CLUSTER}-rw.${NAMESPACE}.svc.cluster.local:5432/very_prince"
